name: pro-2
recipe: drupal9
config:
  webroot: web
services:
  node:
    type: node

  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
proxy:
  phpmyadmin:
    - phpmyadmin.ecom.lndo.site